[package]
name = "recreation-rust-hyper"
version = "1.0.2"
authors = ["Benoit <krazylek@gmail.com>"]

[dependencies]
hyper="0.11"
futures = "0.1"
url="*"
getopts = "0.2"
rand = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
tokio-core = "0.1"